---
- name: Set up MySQL Droplet
  hosts: mysql
  tags:
    - mysql
  roles:
    - role: mysql

- name: Set up Cachet Droplet
  hosts: cachet
  force_handlers: True
  tags:
    - cachet
  roles:
    - role: cachet
