- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload php-fpm
  service:
    name: php7.0-fpm
    state: reloaded

- name: update app
  command: chdir=/var/www/cachet php artisan app:update
  become: true
  become_user: www-data
